sub-PR 4
george-bryan/CM1 pull request #107
Opened 2023-04-25 16:49 UTC by drichte2

Added several more statistics, and created a single 1st order statistics array so that there is only a single mpi_reduce call in droplet_diag

2023-04-25 17:11 UTC, johnmauff requested changes

2023-04-25 17:11 UTC, johnmauff commented on src/droplet.F
> +         do i=1,ni
@drichte2 Could you add the necessary OpenACC directives here?

2023-04-25 17:21 UTC, drichte2 commented on src/droplet.F
> +         do i=1,ni
Do you mean adding `m1src_tmp`, `m2src_tmp`, and `m3src_tmp` into the `reduction` call? I'm not sure what you mean otherwise

2023-04-25 17:24 UTC, sjsprecious commented on src/droplet.F
> +         do i=1,ni
I have just added them.

2023-04-25 19:44 UTC, sjsprecious commented
By using the namelist `namelist.restC` and without the conda environment, the verification result on Casper looks below:

---

CPU (intel, 2 MPI ranks) vs. GPU (nvhpc, 2 MPI ranks + 2 V100 GPUs)

Stat output comparision

Identical variables: 62
variables with rel_diff > 1.e-6: 23
variables with rel_diff <= 1.e-6: 1
four variables with largest error: PPMIN, PPMAX, VOR2KM, DIVMAX

Droplet 0th-order diagnostic comparision

Identical variables: 10
variable with rel_diff > 1.e-6: 2
variable with rel_diff <= 1.e-6: 0
Two variables with largest error: Tpavg (~3.4e-6), radmin (~1.2e-5)

Droplet 1st-order diagnostic comparision

Identical variables: 512
variable with rel_diff > 1.e-6: 0
variable with rel_diff <= 1.e-6: 0

---

Compared to the PR#106, the stat output comparison result shows one fewer identical variable and one more variable with relative difference <1.e-6 (variable name `TKEMAX`). The 0th-order droplet diagnostic shows the same variables with relative difference >1.e-6 but the magnitude here is larger. The 1st-order droplet diagnostic is consistent.

2023-04-26 12:26 UTC, johnmauff commented on src/droplet.F
> +         do i=1,ni
@drichte2, yes,the m1src_tmp, m2src_tmp, and m3src_tmp variables need to be added to the OpenACC directive just like the Tpsrc_tmp and qvsrc_tmp variables.  It looks like Jian beat you to it.

2023-04-26 12:28 UTC, johnmauff approved these changes

2023-04-26 14:21 UTC, sjsprecious approved these changes

2023-04-26 14:21 UTC, merged