Optimization of the fallout_GPU subroutine
george-bryan/CM1 pull request #22
Opened 2021-10-13 15:32 UTC by sherimickelson

2021-10-13 15:33 UTC, sherimickelson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Optimize fallout_GPU on GPU](https://trello.com/c/eaxe6CUe/26-optimize-falloutgpu-on-gpu)

2021-10-18 15:55 UTC, johnmauff commented on src/kessler.F
> +    do n=1,nfall(i,j)
I  don't think you are using the correct value for the bounds on the n-loop nfall(i,j) is using old values for i and j. here

2021-10-18 15:55 UTC, johnmauff commented on src/kessler.F
> +    do n=1,nfall(i,j)
Another bug with loop bounds

2021-10-18 15:56 UTC, johnmauff commented on src/kessler.F
> +    do n=1,nfall(i,j)
Another n-loop bounds error

2021-10-18 15:56 UTC, johnmauff commented on src/kessler.F
> +    do n=1,nfall(i,j)
Another n-loop bounds error

2021-10-18 15:56 UTC, johnmauff requested changes
I think you have a bug here.  The bounds for the outer loop of n is nfall(i,j).  But i and j are not defined properly here.

2021-10-18 19:20 UTC, sherimickelson commented
@johnmauff , Thanks for the catch.  I'll close this PR, fix it, and open a new PR.

2021-10-18 19:20 UTC, closed without merging