Compact the pdata to make active droplets contiguous
george-bryan/CM1 pull request #83
Opened 2022-09-20 19:24 UTC by sjsprecious

This PR compacts the **pdata** to make sure that the active droplets for each MPI rank is contiguous after calling the **droplet_driver** subroutine. Therefore, there will be no *holes* in the **pdata** after the MPI communication.

With these changes, we could perform the droplet calculation for the active droplets only rather than the whole **nparcelsLocal** slots of **pdata**.

The verification tests show a consistent result compared to those using the latest **gpu-opt** branch (commit: `ff1374`)

2022-09-21 21:18 UTC, sherimickelson approved these changes

2022-09-26 21:07 UTC, johnmauff commented on src/droplet.F
> +       do np = 1, nparcelsActive
@sjsprecious It appears that you are looping over the entire collection of droplets looking for holes. Why are you not keeping track of the location of all the holes and then filling them in? Right now operation is O(nparcelsActive) versus what it could be which is O(num_holes)

2022-09-26 21:07 UTC, johnmauff commented on src/comm.F
> +      integer, intent(in), dimension(nparcelsActive) :: pdata_neighbor     ! array to store the new MPI region
Could you clarify if nparcelsActive is really the actual number of active particles or the maximum number of total particles?  If it is the former then why would you dimension arrays a size the should change during execution.

2022-09-26 22:04 UTC, sjsprecious commented on src/comm.F
> +      integer, intent(in), dimension(nparcelsActive) :: pdata_neighbor     ! array to store the new MPI region
`nparcelsActive` is the actual number of active droplets per MPI rank and it varies every time step. I think it is fine (and better) to specify the dimension explicitly as long as we update `nparcelsActive` correctly after the call to `droplet_driver`.

2022-09-27 19:13 UTC, sjsprecious commented on src/droplet.F
> +       do np = 1, nparcelsActive
Thanks for catching this inefficient implementation, @johnmauff ! I have revised the implementation based on your suggestions and the verification results are the same with the latest changes.

2022-09-28 06:39 UTC, sjsprecious commented on src/comm.F
> +      integer, intent(in), dimension(nparcelsActive) :: pdata_neighbor     ! array to store the new MPI region
@johnmauff , I have updated the array dimension to a fixed length as we discussed.

2022-09-28 13:59 UTC, johnmauff requested changes

2022-09-28 13:59 UTC, johnmauff commented on src/droplet.F
>        ELSEIF (idropmethod.eq.1) THEN  !Implicit backward Euler for the droplet integration
@sjsprecious Right now it appears that if the user selects a different droplet time integration method the new MPI implementation will fail right?  I think we should be adding the neighbor array calculation to the rk2_integration time integration method.

2022-09-28 13:59 UTC, johnmauff commented on src/droplet.F
> +    if ( sum(num1) .ne. 0 ) allocate(leave_ind(sum(num1)))
@sjsprecious 
The names of the num{1,2} arrays do not convey what they correspond to in the code.  You also use the calculation sum(num1) and sum(num2) quite frequently.  To make the code more readable I would suggest that you rename these arrays:  num1:= Depart, num2:= Arrive, and also define the new variables numDepart = sum(Depart), numArrive=sum(Arrive)

2022-09-28 13:59 UTC, johnmauff commented on src/droplet.F
> +    if ( sum(num2) .lt. sum(num1) ) then
@sjsprecious I am concerned about what you have done with respect to the hole-filling logic.  In particular, it has been placed in two locations.  Once here where the number of arriving droplets is less than the number of departing, and the other is in the comm.F file. Also, I don't think that the update_new_droplet() subroutine really does not belong in the comm.F file. I view this placement as just very confusing for long-term code maintainability.  We probably need a more involved discussion on this topic.

2022-09-28 14:41 UTC, sjsprecious commented on src/droplet.F
>        ELSEIF (idropmethod.eq.1) THEN  !Implicit backward Euler for the droplet integration
@johnmauff I talked with David once about this issue and he commented that the RK2 solver should be removed sometime in the future. Thus we probably do not want to change it anyway.

2022-09-28 14:53 UTC, sjsprecious commented on src/droplet.F
> +    if ( sum(num1) .ne. 0 ) allocate(leave_ind(sum(num1)))
Thanks for the suggestion. Done.

2022-09-28 16:00 UTC, johnmauff commented on src/droplet.F
> +    if ( sum(num1) .ne. 0 ) allocate(leave_ind(sum(num1)))
Thanks this looks good and makes the code much easier to understand

2022-09-28 16:01 UTC, johnmauff commented on src/comm.F
> +      integer, intent(in), dimension(nparcelsActive) :: pdata_neighbor     ! array to store the new MPI region
Thanks for the code modificaiton.

2022-09-28 16:02 UTC, johnmauff commented on src/droplet.F
> +       do np = 1, nparcelsActive
Great, thanks for reducing the order of the loop.

2022-09-28 18:08 UTC, johnmauff approved these changes
@sjsprecious Thanks for all the changes.  This PR now looks good.

2022-09-28 18:08 UTC, johnmauff commented on src/droplet.F
> +    if ( sum(num2) .lt. sum(num1) ) then
Thanks for moving the hole-filling logic code to a single location in the code

2022-09-28 18:09 UTC, merged